#!/bin/sh
prov=canonical
# Now uses the variable TESTS
export BIN=`pwd`/bin
if test $# -eq 0
then
  echo "You need to give a Version name (or two)!!!"
  exit
fi
newv=$1
if test $# -eq 2
then
  prov=$1
  newv=$2
fi
# Now try and find EXECS to compare
rm -rf etmp$$
touch etmp$$
for e in $TESTS
do
  if test ! -d "$e"
  then
    echo "      ===================================="
    echo "      CASE $e directory does not exist!!!"
    echo "      ===================================="
  else
    cd $e
    ls fort.90.*${newv}* >> ../etmp$$ 2>/dev/null
    cd ..
  fi
done
sort --unique etmp$$ > etmp2$$
newvs=`cat etmp2$$ | sed -e's/fort.90.//'`
rm -rf etmp*
for v in $newvs
do
  echo "++++++++++++++++++++++++++++++++++++++"
  echo "Comparing $prov to $v"
  echo "++++++++++++++++++++++++++++++++++++++"
  tests=`echo "$TESTS" | sed -e's/ *bnl */ /'`
  echo $tests
  for i in $tests
  do
    if test ! -d "$i"
    then
      echo "      ===================================="
      echo "      CASE $i directory does not exist!!!"
      echo "      ===================================="
    else
      echo "      ===================================="
      echo "      CASE $i"
      echo "      ===================================="
      n=90
      while test "$n" -ge 59
      do
        if test -s $i/fort.${n}.$prov
        then 
          if test -s $i/fort.${n}.$v
          then
            mkdir -p tmp$$
            cd tmp$$
            cp ../$i/fort.${n}.$prov fort.190
            $BIN/read90 > fort.20 
            cp ../$i/fort.${n}.$v fort.190
            $BIN/read90 > fort.21 
            diff fort.20 fort.21
            stat=$?
            if test $stat -eq 0
            then
              echo "fort.${n} SAME"
            else
              echo "fort.${n} DIFFERENT!!!"
            fi
            cd   ..
            rm -rf tmp$$
          else
            if test ${n} -eq 90
            then
              echo "      Not yet available $v fort.${n}"
            fi
          fi
        else
          if test ${n} -eq 90
          then
            echo "      Not yet available $prov fort.${n}"
          fi
        fi
        n=`expr $n - 1`
      done
    fi
  done
done
