#!/bin/sh
# this script is exact copy of check_90 
# with the difference that it will
# compare fort.90 from sixtrack stf version with 
# fort.90.stf_canonical in test folders

prov=canonical
use90=false
echo "------------------------------------------------------------"
echo "Usage: ./check_stf (prov=canonical) newv (90)               "
echo
echo "This is for comparing stf version of sixtrack with canonical"
echo "If you haven't chosen single track file flag option then    "
echo "run check_90 instead                                        "
echo
echo "You may give a third argument '90', in which case it will   "
echo " compare the first pair in the new singletrackfile.dat with "
echo " the old fort.90. Example:                                  "
echo " ./check_stf canonical 4242 90                              "
echo "------------------------------------------------------------"
# Now uses the variable TESTS
export BIN=`pwd`/bin
if test $# -eq 0
then
  echo "You need to give a Version name (or two)!!!"
  exit
fi
newv=$1
if test $# -eq 2
then
  prov=$1
  newv=$2
fi
if test $# -eq 3
then
  prov=$1
  newv=$2
  if test $3 -eq "90"
  then
    use90=true
  else
    echo "If 3 arguments, last argument must be '90'"
    exit
  fi
fi
# Now try and find EXECS to compare
rm -rf etmp$$
touch etmp$$
for e in $TESTS
do
  if test ! -d "$e"
  then
    echo "      ===================================="
    echo "      CASE $e directory does not exist!!!"
    echo "      ===================================="
  else
    cd $e
    ls singletrackfile.dat.*${newv}* >> ../etmp$$ 2>/dev/null
    cd ..
  fi
done
sort --unique etmp$$ > etmp2$$
newvs=`cat etmp2$$ | sed -e's/singletrackfile.dat.//'`
rm -rf etmp*
for v in $newvs
do
  echo "++++++++++++++++++++++++++++++++++++++"
  echo "Comparing $prov to $v"
  echo "++++++++++++++++++++++++++++++++++++++"
  tests=`echo "$TESTS" | sed -e's/ *bnl */ /'`
  echo $tests
  for i in $tests
  do
    if test ! -d "$i"
    then
      echo "      ===================================="
      echo "      CASE $i directory does not exist!!!"
      echo "      ===================================="
    else
      echo "      ===================================="
      echo "      CASE $i"
      echo "      ===================================="
      if [[ (( $use90 = false && -s $i/singletrackfile.dat.$prov )) || (( $use90 = true && -s $i/fort.90.$prov )) ]]
      then 
          if test -s $i/singletrackfile.dat.$v
          then
              mkdir -p tmp$$
              cd tmp$$
	      #echo `pwd`

	      if [ $use90 = false ]; then
		  cp ../$i/singletrackfile.dat.$prov .
		  $BIN/read90 --STF --fname singletrackfile.dat.$prov > singletrackfile.dat.$prov.txt

		  cp ../$i/singletrackfile.dat.$v .
		  $BIN/read90 --STF --fname singletrackfile.dat.$v > singletrackfile.dat.$v.txt

		  diff singletrackfile.dat.$prov.txt singletrackfile.dat.$v.txt
		  stat=$?
		  
	      elif [ $use90 = true ]; then
		  cp ../$i/fort.90.$prov .
		  $BIN/read90 --fname fort.90.$prov > fort.90.$prov.txt

		  cp ../$i/singletrackfile.dat.$v .
		  $BIN/read90 --STF --SP 1 --fname singletrackfile.dat.$v > singletrackfile.dat.$v.txt

		  
		  diff fort.90.$prov.txt singletrackfile.dat.$v.txt
		  stat=$?

	      else
		  echo "Error, expected $use90 to be either 'true' or 'false', got '"$use90"'"
		  exit
	      fi
		  
              if test $stat -eq 0
              then
		  echo "singletrackfile.dat SAME"
              else
		  echo "singletrackfile.dat DIFFERENT!!!"
              fi
              cd   ..
              rm -rf tmp$$
          else
		  echo "      Not yet available $v singletrackfile.dat"
          fi
      else
              echo "      Not yet available $prov singletrackfile.dat"
      fi
    fi
  done
done
