#!/bin/sh
#
# BUT must NOT touch fort.90 or other binaries
find . -type f > all$$ 
while read afile
do
  file $afile | grep ASCII | grep CRLF > /dev/null
  if test $? -eq 0
  then
    echo "Removing CRLF from $afile"
    winremover $afile
  fi
done < all$$
rm all$$
