#!/bin/sh
set -x
if test $# -ne 3
then
  echo "try_coll called without 3 parameters!!!"
  exit 1
fi
#
sixdir=$1
sixv=$2
dir=$3
COLL=""
echo $sixv | grep 'coll' >/dev/null
if test $? -eq 0
then
  COLL="COLL"
else
  echo "The sixtrack version specified is not for Collimation!"
  exit 2
fi
date
echo "===================================="
echo "Testing Version $sixv"
echo "===================================="
echo "=== `hostname` ==="
egrep 'model name' /proc/cpuinfo
egrep 'cpu MHz|cache size' /proc/cpuinfo
esize=`size -d $sixdir/$sixv|sed -e'/dec/d' -e's/\t/ /g' -e's/  */ /'|cut -d" " -f1-4`
echo ""
echo "Size of $sixv $esize"
for i in coll
do
  echo "===================================="
  echo "Testing CASE $i"
  echo "===================================="
  echo "=== $dir ==="
  rm -f fort.*
  for j in 2 3 8 16
  do
    cp ../$i/fort.$j fort.$j
  done
  if test "$i" = "bnl"
  then
    cp ../$i/beambeamdist.dat beambeamdist.dat
  fi
  echo "First (only) time pro, no checkpoints"
  if test "$i" = "coll"
  then
    cp ../$i/CollDB_V6.500_lowb_st.b1.data CollDB_V6.500_lowb_st.b1.data
  fi
  date
  time ../runsix_pro $sixdir $sixv
  date
  egrep 'Computing Time|Total Time' fort.6
  cp fort.6 ../$i/fort.6.$dir
  cp fort.10 ../$i/fort.10.$dir
  if test "$i" = "bnl"
  then
    if test "$CPSS" != ""
    then
      cp fort.10 ../$i/title.dat.$dir
      cp fort.52 ../$i/beambeam-output.dat.$dir
      cp fort.53 ../$i/beambeam-lostID.dat.$dir
      cp fort.51 ../$i/SixTwiss.dat.$dir
      cp fort.97 ../$i/checkdist.dat.$dir
    elif test "$BOINC" != ""
    then
      egrep 'title     ' fort.10 > tmp$$
      sed -e's/title     //' tmp$$ > ../$i/title.dat.$dir
      egrep 'output    ' fort.10 > tmp$$
      sed -e's/output    //' tmp$$ > ../$i/beambeam-output.dat.$dir
      egrep 'lostID    ' fort.10 tmp$$ > tmp$$
      sed -e's/lostID    //' tmp$$ > ../$i/beambeam-lostID.dat.$dir
      egrep 'checkdist ' fort.10 > tmp$$
      sed -e's/checkdist //' tmp$$ > ../$i/checkdist.dat.$dir
      egrep 'Sixtwiss  ' fort.10 > tmp$$
      sed -e's/SixTwiss  //' tmp$$ > ../$i/SixTwiss.dat.$dir
      rm tmp$$
    else
      cp fort.10 ../$i/title.dat.$dir
      cp beambeam-output.dat ../$i/beambeam-output.dat.$dir
      cp beambeam-lostID.dat ../$i/beambeam-lostID.dat.$dir
      cp SixTwiss.dat ../$i/SixTwiss.dat.$dir
      cp checkdist.dat ../$i/checkdist.dat.$dir
    fi
  fi
done
