!FOX  B D ;
!FOX  D V DA COM SIGMDA NORD NVAR ; D V DA COM DPDA NORD NVAR ;
!FOX  D V DA COM KCRABDA NORD NVAR ; D V DA COM DELTAS NORD NVAR ;
!FOX  D V DA COM DPDA1 NORD NVAR ; D V DA COM RV NORD NVAR ;
!FOX  D V DA COM XX NORD NVAR 2 ; D V DA COM YY NORD NVAR 2 ;
!FOX  D V DA COM EJ1 NORD NVAR ; D V DA COM EJF1 NORD NVAR ;
!FOX  D V DA COM ALDA NORD NVAR 2 6 ; D V DA COM ASDA NORD NVAR 2 6 ;
!FOX  D V DA COM ALDAQ NORD NVAR 2 6 ; D V DA COM ASDAQ NORD NVAR 2 6 ;
!FOX  D V DA COM SMIDA NORD NVAR MCOR ; D V DA COM MOIDA NORD NVAR ;
!FOX  D V DA INT X NORD NVAR 2 ; D V DA INT Y NORD NVAR 2 ;
!FOX  D V DA INT YP NORD NVAR 2 ; D V DA INT DKIP NORD NVAR ;
!FOX  D V DA INT CORROLD NORD NVAR MCOP ;  D V RE INT MTCDA ;
!FOX  D V DA INT CORRNEW NORD NVAR MCOP ;
!FOX  D V DA INT CORRAU1 NORD NVAR MCOP ;
!FOX  D V DA INT CORRAU2 NORD NVAR MCOP ;
!FOX  D V DA INT AA NORD NVAR 11 ;  D V DA INT BB NORD NVAR 11 ;
!FOX  D V DA INT TRACKI NORD NVAR 6 ;
!FOX  D V DA INT TEMPI NORD NVAR 6 ;
!FOX  D V DA INT PUX NORD NVAR ; D V DA INT PUZ NORD NVAR ;
!FOX  D V DA INT PUSIG NORD NVAR ;
!FOX  D V DA INT EJF0 NORD NVAR ; D V DA INT EKK NORD NVAR ;
!FOX  D V DA INT XL NORD NVAR ; D V DA INT ZL NORD NVAR ;
!FOX  D V DA INT CRKVE NORD NVAR ; D V DA INT CIKVE NORD NVAR ;
!FOX  D V DA INT CRKVEUK NORD NVAR ; D V DA INT CBZBF NORD NVAR ;
!FOX  D V DA INT YV1J NORD NVAR ; D V DA INT YV2J NORD NVAR ;
!FOX  D V DA INT CRKVEBF NORD NVAR ; D V DA INT CIKVEBF NORD NVAR ;
!FOX  D V DA INT RHO2BF NORD NVAR ; D V DA INT TKBF NORD NVAR ;
!FOX  D V DA INT XRBF NORD NVAR ; D V DA INT CCCC NORD NVAR ;
!FOX  D V DA INT ZRBF NORD NVAR ; D V DA INT XBBF NORD NVAR ;
!FOX  D V DA INT ZBBF NORD NVAR ; D V DA INT CRXBF NORD NVAR ;
!FOX  D V DA INT CBXBF NORD NVAR ; D V DA INT CRZBF NORD NVAR ;
!FOX  D V DA INT WX NORD NVAR ; D V DA INT WY NORD NVAR ;
!FOX  D V DA INT CRABAMP NORD NVAR ;
!FOX  D V DA INT CRABAMP2 NORD NVAR ;
!FOX  D V DA INT CRABAMP3 NORD NVAR ;
!FOX  D V DA INT CRABAMP4 NORD NVAR ;

!FOX  D V DA INT NORMALDA NORD NVAR MMUL ;
!FOX  D V DA INT SKEWDA NORD NVAR MMUL ;
!FOX  D V DA INT PSIDA NORD NVAR MMUL ;
!FOX  D V DA INT PNLDA NORD NVAR MMUL ;


!solenoid ONEDPDA,FPPSIGDA,COSTH_DA,SINTH_DA,Q_DA,R_DA,Z_DA,PXFDA,PYFDA,SIGFDA
!FOX  D V DA COM ONEDPDA NORD NVAR ; D V DA COM SINTH_DA NORD NVAR ;

!FOX  D V DA COM Q_DA NORD NVAR ;
!FOX  D V DA COM FPPSIGDA NORD NVAR ; D V DA COM R_DA NORD NVAR ;
!FOX  D V DA COM COSTH_DA NORD NVAR ; D V DA COM Z_DA NORD NVAR ;
!FOX  D V DA COM PXFDA NORD NVAR ; D V DA COM PYFDA NORD NVAR ;
!FOX  D V DA COM SIGFDA NORD NVAR ;


!FOX  D V RE INT AAIV MMUL NBLZ ; D V RE INT BBIV MMUL NBLZ ;

!FOX  D V RE INT NORRFAMP MMUL NBLZ ; D V RE INT NORRFPH MMUL NBLZ ;
!FOX  D V RE INT SKRFAMP MMUL NBLZ ; D V RE INT SKRFPH MMUL NBLZ ;

!FOX  D V RE INT TILTC NBLZ ; D V RE INT TILTS NBLZ ;
!FOX  D V RE INT DPS MPA ; D V RE INT SIGM MPA ;
!FOX  D V RE INT DKI NELE 3 ; D V RE INT BL1 NBLO 2 6 ;
!FOX  D V RE INT EL NELE ; D V RE INT EJ MPA ; D V RE INT EJF MPA ;
!FOX  D V RE INT SMI NBLZ ; D V RE INT SMIZF NBLZ ;
!FOX  D V RE INT ED1 ; D V RE INT ED2 ;
!FOX  D V RE INT DPDAV2 6 ; D V RE INT RRTR NTR 6 6 ;
!FOX  D V RE INT COTR NTR 6 ; D V RE INT DPDAV ; D V RE INT BETR0 ;
!FOX  D V RE INT E0 ; D V RE INT E0F ;
!FOX  D V RE INT XS ; D V RE INT ZS ; D V RE INT OX ; D V RE INT OXP ;
!FOX  D V RE INT OZ ; D V RE INT OZP ; D V RE INT SIGM1 ;
!FOX  D V RE INT BEAMOFF1 ; D V RE INT BEAMOFF2 ; D V RE INT BEAMOFF3 ;
!FOX  D V RE INT BEAMOFF4 ; D V RE INT BEAMOFF5 ; D V RE INT BEAMOFF6 ;
!FOX  D V RE INT DPS1 ; D V RE INT RKBF ; D V RE INT RBF ;
!FOX  D V RE INT R2BF ; D V RE INT BBCU NBB 12 ;
!FOX  D V RE INT SIGMAN 2 NBB ; D V RE INT PTNFAC NELE ;
!FOX  D V RE INT CRAD ; D V RE INT GAMMAR ; D V RE INT PARBE NELE 18 ;
!FOX  D V RE INT PARTNUM ; D V RE INT PISQRT ; D V RE INT SCRKVEB ;
!FOX  D V RE INT SCIKVEB ; D V RE INT STARTCO ; D V RE INT RATIOE NELE ;
!FOX  D V RE INT PARBE14 ; D V RE INT PI ; D V RE INT NUCM0 ;
!FOX  D V RE INT SIGMDAC ; D V RE INT DUMMY ; D V RE INT MTCDA ;
!FOX  D V RE INT ED NELE ; D V RE INT EK NELE ;
!FOX  D V RE INT WIRECLO0 ;  D V RE INT NUCMDA ;
#ifndef FAST
!FOX  D V RE INT C2E3 ; D V RE INT C1E6 ;
#else
!FOX  D V RE INT C5M4 ; D V RE INT C2E3 ; D V RE INT C1E6 ;
#endif
!FOX  D V RE INT C1E3 ; D V RE INT C1M3 ; D V RE INT C1M6 ;
!FOX  D V RE INT C1M9 ; D V RE INT C1M12 ; D V RE INT C1M15 ;
!FOX  D V RE INT C1M18 ; D V RE INT C1M21 ; D V RE INT C1M24 ;
!FOX  D V RE INT ONE ; D V RE INT TWO ; D V RE INT THREE ;
!FOX  D V RE INT FOUR ; D V RE INT ZERO ; D V RE INT HALF ;
!FOX  D V RE INT CRABFREQ ; D V RE INT CRABPHT ;
!FOX  D V RE INT CRABPHT2 ; D V RE INT CRABPHT3 ;
!FOX  D V RE INT CRABPHT4 ; D V RE INT KCRAB ;
!FOX  D V RE INT CLIGHT ; D V RE INT ZZ0 ;
!FOX  D V IN INT IDZ 2 ; D V IN INT KX ; D V IN INT IX ; D V IN INT JX ;
!FOX  D V IN INT I ; D V IN INT IPCH ; D V IN INT K ; D V IN INT KKK ;
!FOX  D V IN INT IVAR ; D V IN INT IRRTR ; D V IN INT KK ;
!FOX  D V IN INT IMBB NBLZ ;
!FOX  D V IN INT WIRE_NUM NBLZ ;
!FOX  D F RE DARE 1 ;
!FOX  D V DA INT PZ NORD NVAR ;
!FOX  E D ;
