! start include/kicka08v.f90
#ifndef TILT
  mpe=8
  mx=6
  cxzr=xl
  cxzi=zl
  cxzyr=cxzr**2-cxzi**2                                            !hr08
  cxzyi=cxzr*cxzi+cxzi*cxzr
  ab1(6)=(21.0_fPrec*ekk)*cxzyi                                          !hr02
  ab2(6)=(21.0_fPrec*ekk)*cxzyr                                          !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(5)=(35.0_fPrec*ekk)*cxzyi                                          !hr02
  ab2(5)=(35.0_fPrec*ekk)*cxzyr                                          !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(4)=(35.0_fPrec*ekk)*cxzyi                                          !hr02
  ab2(4)=(35.0_fPrec*ekk)*cxzyr                                          !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(3)=(21.0_fPrec*ekk)*cxzyi                                          !hr02
  ab2(3)=(21.0_fPrec*ekk)*cxzyr                                          !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  qu=(seven*ekk)*cxzyi                                               !hr02
  qv=(-seven*ekk)*cxzyr                                              !hr02
  ab2(2)=-one*qv                                                   !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  dyy1=ekk*cxzyi
  dyy2=ekk*cxzyr
  ab1(7)=(seven*ekk)*zl                                              !hr02
  ab2(7)=(seven*ekk)*xl                                              !hr02
  ab2(8)=ekk
#else
  mpe=8
  mx=6
  cxzr=xl
  cxzi=zl
  cxzyr=cxzr**2-cxzi**2                                            !hr08
  cxzyi=cxzr*cxzi+cxzi*cxzr
  tiltck=tiltc(k)**2-tilts(k)**2                                   !hr08
  tiltsk=(two*tiltc(k))*tilts(k)                                   !hr02
  tiltckuk=tiltck*tiltc(k)-tiltsk*tilts(k)
  tiltsk1=tiltck*tilts(k)+tiltsk*tiltc(k)
  tiltck1=tiltckuk
  tiltckuk=tiltck1*tiltc(k)-tiltsk1*tilts(k)
  tiltsk2=tiltck1*tilts(k)+tiltsk1*tiltc(k)
  tiltck2=tiltckuk
  tiltckuk=tiltck2*tiltc(k)-tiltsk2*tilts(k)
  tiltsk3=tiltck2*tilts(k)+tiltsk2*tiltc(k)
  tiltck3=tiltckuk
  tiltckuk=tiltck3*tiltc(k)-tiltsk3*tilts(k)
  tiltsk4=tiltck3*tilts(k)+tiltsk3*tiltc(k)
  tiltck4=tiltckuk
  ab1(6)=(21.0_fPrec*ekk)*(tiltck4*cxzyi-tiltsk4*cxzyr)                  !hr02
  ab2(6)=(21.0_fPrec*ekk)*(tiltck4*cxzyr+tiltsk4*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(5)=(35.0_fPrec*ekk)*(tiltck3*cxzyi-tiltsk3*cxzyr)                  !hr02
  ab2(5)=(35.0_fPrec*ekk)*(tiltck3*cxzyr+tiltsk3*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(4)=(35.0_fPrec*ekk)*(tiltck2*cxzyi-tiltsk2*cxzyr)                  !hr02
  ab2(4)=(35.0_fPrec*ekk)*(tiltck2*cxzyr+tiltsk2*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(3)=(21.0_fPrec*ekk)*(tiltck1*cxzyi-tiltsk1*cxzyr)                  !hr02
  ab2(3)=(21.0_fPrec*ekk)*(tiltck1*cxzyr+tiltsk1*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  qu=(seven*ekk)*(tiltck*cxzyi-tiltsk*cxzyr)                         !hr02
  qv=(-seven*ekk)*(tiltck*cxzyr+tiltsk*cxzyi)                        !hr02
  ab1(2)=qu
  ab2(2)=-one*qv                                                   !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  dyy1=ekk*(tiltc(k)*cxzyi-tilts(k)*cxzyr)
  dyy2=ekk*(tiltc(k)*cxzyr+tilts(k)*cxzyi)
  tiltckuk=tiltck4*tiltc(k)-tiltsk4*tilts(k)
  tiltsk=tiltck4*tilts(k)+tiltsk4*tiltc(k)
  tiltck=tiltckuk
  ab1(7)=(seven*ekk)*(tiltck*zl-tiltsk*xl)                           !hr02
  ab2(7)=(seven*ekk)*(tiltck*xl+tiltsk*zl)                           !hr02
  tiltckuk=tiltck*tiltc(k)-tiltsk*tilts(k)
  tiltsk=tiltck*tilts(k)+tiltsk*tiltc(k)
  tiltck=tiltckuk
  ab1(8)=ekk*tiltsk
  ab2(8)=ekk*tiltck
#endif
! end include/kicka08v.f90
