! start include/kicka07h.f90
#ifndef TILT
  mpe=7
  mx=5
  cxzr=xl
  cxzi=zl
  cxzyr=cxzr**2-cxzi**2                                            !hr08
  cxzyi=cxzr*cxzi+cxzi*cxzr
  ab1(5)=(15.0_fPrec*ekk)*cxzyr                                          !hr02
  ab2(5)=(-15.0_fPrec*ekk)*cxzyi                                         !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(4)=(20.0_fPrec*ekk)*cxzyr                                          !hr02
  ab2(4)=(-20.0_fPrec*ekk)*cxzyi                                         !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(5)=(15.0_fPrec*ekk)*cxzyr                                          !hr02
  ab2(5)=(-15.0_fPrec*ekk)*cxzyi                                         !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  qu=(six*ekk)*cxzyr                                               !hr02
  qv=(six*ekk)*cxzyi                                               !hr02
  ab2(2)=-one*qv                                                   !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  dyy1=ekk*cxzyr
  dyy2=(-one*ekk)*cxzyi                                            !hr02
  ab1(6)=(six*ekk)*xl                                              !hr02
  ab2(6)=(-six*ekk)*zl                                             !hr02
  ab1(7)=ekk
#else
  mpe=7
  mx=5
  cxzr=xl
  cxzi=zl
  cxzyr=cxzr**2-cxzi**2                                            !hr08
  cxzyi=cxzr*cxzi+cxzi*cxzr
  tiltck=tiltc(k)**2-tilts(k)**2                                   !hr08
  tiltsk=(two*tiltc(k))*tilts(k)                                   !hr02
  tiltckuk=tiltck*tiltc(k)-tiltsk*tilts(k)
  tiltsk1=tiltck*tilts(k)+tiltsk*tiltc(k)
  tiltck1=tiltckuk
  tiltckuk=tiltck1*tiltc(k)-tiltsk1*tilts(k)
  tiltsk2=tiltck1*tilts(k)+tiltsk1*tiltc(k)
  tiltck2=tiltckuk
  tiltckuk=tiltck2*tiltc(k)-tiltsk2*tilts(k)
  tiltsk3=tiltck2*tilts(k)+tiltsk2*tiltc(k)
  tiltck3=tiltckuk
  ab1(5)=(15.0_fPrec*ekk)*(tiltck3*cxzyr+tiltsk3*cxzyi)                  !hr02
  ab2(5)=(15.0_fPrec*ekk)*(tiltsk3*cxzyr-tiltck3*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(4)=(20.0_fPrec*ekk)*(tiltck2*cxzyr+tiltsk2*cxzyi)                  !hr02
  ab2(4)=(20.0_fPrec*ekk)*(tiltsk2*cxzyr-tiltck2*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  ab1(5)=(15.0_fPrec*ekk)*(tiltck1*cxzyr+tiltsk1*cxzyi)                  !hr02
  ab2(5)=(15.0_fPrec*ekk)*(tiltsk1*cxzyr-tiltck1*cxzyi)                  !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  qu=(six*ekk)*(tiltck*cxzyr+tiltsk*cxzyi)                         !hr02
  qv=(six*ekk)*(tiltck*cxzyi-tiltsk*cxzyr)                         !hr02
  ab1(2)=qu
  ab2(2)=-one*qv                                                   !hr02
  cxzyrr=cxzyr*cxzr-cxzyi*cxzi
  cxzyi=cxzyr*cxzi+cxzyi*cxzr
  cxzyr=cxzyrr
  dyy1=ekk*(tiltc(k)*cxzyr+tilts(k)*cxzyi)
  dyy2=ekk*(tilts(k)*cxzyr-tiltc(k)*cxzyi)                         !hr02
  tiltckuk=tiltck3*tiltc(k)-tiltsk3*tilts(k)
  tiltsk=tiltck3*tilts(k)+tiltsk3*tiltc(k)
  tiltck=tiltckuk
  ab1(6)=(six*ekk)*(tiltck*xl+tiltsk*zl)                           !hr02
  ab2(6)=(six*ekk)*(tiltsk*xl-tiltck*zl)                           !hr02
  tiltckuk=tiltck*tiltc(k)-tiltsk*tilts(k)
  tiltsk=tiltck*tilts(k)+tiltsk*tiltc(k)
  tiltck=tiltckuk
  ab1(7)=ekk*tiltck
  ab2(7)=ekk*tiltsk
#endif
! end include/kicka07h.f90
