#ifndef TILT
!FOX  Y(1)=Y(1)+BBIV(1,I)*MTCDA/(ONE+DPDA) ;
!FOX  Y(2)=Y(2)+AAIV(1,I)*MTCDA/(ONE+DPDA) ;
#else
!FOX  Y(1)=Y(1)+(TILTC(I)*BBIV(1,I)-TILTS(I)*AAIV(1,I))*MTCDA/(ONE+DPDA) ;
!FOX  Y(2)=Y(2)+(TILTC(I)*AAIV(1,I)+TILTS(I)*BBIV(1,I))*MTCDA/(ONE+DPDA) ;
#endif
