#!/usr/bin/env bash

tag=$1
COMMIT_HASH=$2

pull_request=`git log -n1 $COMMIT_HASH | grep "Merge pull request" | grep -o "#[0-9]*"`

if [[ ! -z $pull_request ]]
then
  echo "Pull request $pull_request"
  git tag -a $tag $COMMIT_HASH -m $tag
  GIT_COMMITTER_DATE="$(git show $COMMIT_HASH --format=%aD | head -1)" git tag -a -f $tag -m"$tag" $COMMIT_HASH
  git push upstream $tag
else
  echo "wrong commit hash $COMMIT_HASH"
fi

vnumber=`echo $tag| sed 's/v//;s/\.//g'`


public_dir=/afs/cern.ch/project/sixtrack/build/$vnumber/x86_64-pc-linux-gnu__sse2
mkdir -p $public_dir

./cmake_six
cp SixTrack_cmakesix_defaultcompiler_defaultbuildtype/SixTrack_$vnumber* $public_dir

./buildLibraries.sh
./cmake_six BOINC API LIBARCHIVE CR BIGNBLZ
cp SixTrack_cmakesix_API_BIGNBLZ_BOINC_CR_LIBARCHIVE_defaultcompiler_defaultbuildtype/SixTrack_$vnumber* $public_dir

ls $public_dir
