#! /usr/bin/env bash

# make_six-like wrapper for cmake and make
# 

set -e

echo "Welcome to cmake_six, camouflaging cmake and make inside the same interface as make_six !"

#Run the Beauty "linters"
if [ -x "$(command -v gawk)" ]; then
    echo ""
    echo "Running 'gawk -f beauty/count.awk sixtrack.s' to check sanity of astuce directives in sixtrack.s:"
    if ! gawk -f beauty/count.awk sixtrack.s; then
	echo -e "\e[5m\e[41m WARNING: ASTUCE if/ei doesn't match up in sixtrack.s \e[49m\e[0m"
	echo "This most likely means that you added or removed a +if or +ei,"
	echo " but forgot about its partner."
	echo "You may also just be missing the command 'gawk' (GNU AWK),"
	echo " needed to run this script."
    else
	echo "--> count.awk completed without errors."
    fi
    echo "Running 'gawk -f beauty/check_astuce_ifs.awk sixtrack.s' to check sanity of astuce directives in sixtrack.s:"
    if ! gawk -f beauty/check_astuce_ifs.awk sixtrack.s; then
	echo -e "\e[5m\e[41m WARNING: ASTUCE if has too many arguments in sixtrack.s \e[49m\e[0m"
	echo "This most likely means that you have an extra space in an astuce +if statement"
	echo "You may also just be missing the command 'gawk' (GNU AWK),"
	echo " needed to run this script."
    else
	echo "--> check_astuce_ifs.awk completed without errors."
    fi
    echo "Running 'gawk -f beauty/count.awk plato_seq.s' to check sanity of astuce directives in plato_seq.s:"
    if ! gawk -f beauty/count.awk plato_seq.s; then
	echo -e "\e[5m\e[41m WARNING: ASTUCE if/ei doesn't match up in plato_seq.s \e[49m\e[0m"
	echo "This most likely means that you added or removed a +if or +ei,"
	echo " but forgot about its partner."
	echo "You may also just be missing the command 'gawk' (GNU AWK),"
	echo " needed to run this script."
    else
	echo "--> count.awk completed without errors."
    fi
    echo "Running 'gawk -f beauty/check_astuce_ifs.awk plato_seq.s' to check sanity of astuce directives in sixtrack.s:"
    if ! gawk -f beauty/check_astuce_ifs.awk plato_seq.s; then
	echo -e "\e[5m\e[41m WARNING: ASTUCE if has too many arguments in plato_seq.s \e[49m\e[0m"
	echo "This most likely means that you have an extra space in an astuce +if statement"
	echo "You may also just be missing the command 'gawk' (GNU AWK),"
	echo " needed to run this script."
    else
	echo "--> check_astuce_ifs.awk completed without errors."
    fi
else
    echo
    echo "WARNING: You have not installed gawk (GNU AWK)."
    echo "This is needed to check the correctness of the ASTUCE +if /+ei"
    echo "If you are modifying the .s files, it is STRONGLY RECCOMENDED to install gawk"
fi

#Get options

compilers=(gfortran ifort ifort_icc nagfor) # Valid compilers
options_COMPILER=notset #which compilers to use

options_ALL=() # All set options
options_ON=()  # All options switched ON
options_OFF=() # All options switched OFF

for var in "$@" #Loop over command line arguments
do
    if [[ $var == -* ]]; then ## Negative options
	#echo "OFF" $var
	varOn=${var:1} # Without the "-"
	for v in ${options_ALL[@]}
	do
	    if [[ $v == $varOn ]]; then
		echo "ERROR: option $v used more than once"
		exit 1
	    fi
	done

	for v in ${compilers[@]}
	do
	    if [[ $v == $varOn ]]; then
		echo "ERROR: can't switch a compiler off"
		exit 1
	    fi
	done
	
	options_ALL+=(${var:1})
	
    else                      ## Positive options
	#echo "ON" $var
	varOn=$var
	for v in ${options_ALL[@]}
	do
	    if [[ $v == $varOn ]]; then
		echo "ERROR: option $v used more than once"
		exit 1
	    fi
	done

	thisWasCompiler="NO"
	for v in ${compilers[@]}
	do
	    if [[ $v == $varOn ]]; then
		if [[ $options_COMPILER != "notset" ]]; then
		    echo "ERROR: can't set multiple compilers"
		    exit 1
		fi
		options_COMPILER=$varOn
		thisWasCompiler="YES"				    
	    fi
	done

	if [[ $thisWasCompiler == "NO" ]]; then
	    options_ALL+=($var)
	fi
	thisWasCompiler="NO"
    fi
done

echo "got:"
for var in ${options_ALL[@]}
do
    echo $var
done


#Run cmake
#Run make
