#!/bin/sh
where="$1"
if test $# -ne 1
then
  echo "You must specify the directory to compare with ".""
  exit
fi
for i in dabnew  dabnews  lielib  share  sixda  sixscfox  sixve  sixvefox  track
do
  echo "=================="
  echo "$i.f"
  echo "=================="
  diff $i.f $where/$i.f
done
