#!/bin/sh
#
set -x
# This does every elementary function including multiple
# occurrences - it does NOT make double precision defs for _rn
# It can be used on .s but MUST use a ; to inhibit +if
# and then remove it afterwards. 
# the lout  and trig common blocks
./doflags
# It splits lines for ease of comparison (NOT to be done with .s)
./dotrig
# This replaces all prints (sedprint) and write 6/* 100/'format'
./dow6
# Fix up sythckcr
./dosyn
#This does tle1=log..., rv/rvv, and stop to abend
./domisc
#
./doflush
# need to fix up commons etc (done in deck checkpt)
# Now add in new deck checkpt (inclduing abend.f)
cat sixnov04.s base/checkpt > tmp
mv tmp sixnov04.s  
