#!/bin/sh
# Do all crlibm stuff, with NO line splitting and global replacement
#
set -x
for j in `ls *.s`
do
###for i in sin cos tan asin acos atan sinh cosh atan2 log log10 exp
  count=0
  stat=1
  while test "$stat" -ne 0
  do
    sed -f sedtrig $j > tmp
    count=`expr $count + 1`
    diff $j tmp > /dev/null
    if test $? -eq 0
    then
      stat=0
    else
      mv tmp $j
    fi
  done 
  echo "$j, count=$count"
  sed -f sedsemi $j > tmp
  mv tmp $j
done
