#!/bin/sh
# Do all formatted writes to 6 or * with format statement or quoted format
#
#for j in dabnews.f datime.f lielib.f plotdumy.f sixve.f sixvefox.f timest.f timex.f track.f
for j in `ls *.s`
do
  sed -f sedprint $j > tmp
  mv tmp $j 
  sed -f sedw6 $j > tmp
  mv tmp $j
done
