#!/bin/sh

export TESTS="$PROTESTS"

export EXECS=$SH0/SixTrack_4493_crlibm_bnl_gfortran_O4/SixTrack_4493_crlibm_bnl_gfortran_O4
file $EXECS
export EXECS=$SH0/SixTrack_4493_crlibm_bnl_nagfor_O/SixTrack_4493_crlibm_bnl_nagfor_O
file $EXECS
export EXECS=$SH0/SixTrack_4493_crlibm_bnl_lf95_o0/SixTrack_4493_crlibm_bnl_lf95_o0
file $EXECS
export EXECS=$SH0/SixTrack_4493_crlibm_bnl_pgf90_O0/SixTrack_4493_crlibm_bnl_pgf90_O0
file $EXECS
export EXECS=$SH0/SixTrack_4493_crlibm_bnl_ifort_O/SixTrack_4493_crlibm_bnl_ifort_O
file $EXECS
