#!/bin/sh
#set -x #Xtrace on (for debugging)
prov=canonical
# Now uses the variable TESTS
export BIN=`pwd`/bin
if test $# -eq 0
then
  echo "You need to give a Version name (or two)!!!"
  exit
fi
newv=$1
if test $# -eq 2
then
  prov=$1
  newv=$2
fi
# Now try and find EXECS to compare
rm -rf etmp$$
touch etmp$$
for e in $TESTS
do
  if test ! -d "$e"
  then
    echo "      ===================================="
    echo "      CASE $e directory does not exist!!!"
    echo "      ===================================="
  else
    #There may be several versions of the new version!
    #But they should all make a fort.10, so this is an acceptable way
    #of finding the names of the new versions.
    cd $e
    ls fort.10.*${newv}* >> ../etmp$$ 2>/dev/null
    cd ..
  fi
done
sort --unique etmp$$ > etmp2$$
newvs=`cat etmp2$$ | sed -e's/fort.10.//'`
rm -rf etmp*
#BNL="bnl"
#mybnl=`echo "$newv" | grep 'bnl'`
#if test "$mybnl" = ""
#then
#  BNL=""
#fi
for v in $newvs
do
  echo "++++++++++++++++++++++++++++++++++++++"
  echo "Comparing $prov to $v"
  echo "++++++++++++++++++++++++++++++++++++++"
  tests="$TESTS"
  for i in $tests
  do
    if test ! -d "$i"
    then
      echo "      ===================================="
      echo "      CASE $i directory does not exist!!!"
      echo "      ===================================="
    else
      echo "      ===================================="
      echo "      CASE $i"
      echo "      ===================================="

      #Get the names of the files to check
      if test ! -s $i/extra_checks.txt; then
        echo "No extra_checks.txt in this folder, skipping!"
        continue
      fi

      FAIL=N
      
      echo "Reading $i/extra_checks.txt"
      set -f #Disable wildcard expansion
      while read checkfile command; do
         echo "Got file :: command = " $checkfile :: $command
         if test ! "$checkfile" -o ! "$command" ; then
            echo "   Invalid line."
	    continue
	 fi

	 if ! test -f $i/$checkfile.$prov ; then
	     echo -e "\e[91mCanonical $i/$checkfile.$prov not found, skipping \e[39m"
	     FAIL=Y
	     continue
	 fi
	 if ! test -f $i/$checkfile.$v ; then
	     echo -e "\e[91mTest file $i/$checkfile.$v not found, skipping \e[39m"
	     FAIL=Y
	     continue
	 fi
	 
	 # Todo: Work in tmp folder, like for check_10

	 COMMAND="$command $i/$checkfile.$prov $i/$checkfile.$v"
	 echo "Running '$COMMAND'":
	 RESULTS=$($COMMAND)
	 echo $RESULTS
	 if [ "$RESULTS" != "" ] ; then
	     echo
	     echo -e "\e[91mFiles '$i/$checkfile.$prov' and '$i/$checkfile.$v' are DIFFERENT!! \e[39m"
	     FAIL=Y
	     echo
	 fi
      done < $i/extra_checks.txt
      set +f #Renable wildcards (glob)

      if [ $FAIL = "Y" ]; then
	  echo -e "\e[91m      *****************************************\e[39m"
	  echo -e "\e[91m      Test $i FAILED\e[39m"
	  echo -e "\e[91m      *****************************************\e[39m"
      else
	  echo -e "\e[92m      *****************************************\e[39m"
	  echo -e "\e[92m      Test $i SUCESS\e[39m"
	  echo -e "\e[92m      *****************************************\e[39m"
      fi
    fi
  done
done
