#!/bin/sh
# A script to build SixTrack with ifort (Lahey ?)
echo "Trying to build SixTrack SixTrack_4535_cernlib_crlibm_gfortran_O4"
cd crlibm
make clean
make
cp *.o ..
cd ..
./compile_fortran.bat
./link_intel.bat
